/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Asterid_explodable.glb -o src/components/Ateroid.jsx -r public -k 
*/
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import { MathUtils, Vector3 } from 'three'

const DISINTEGRATE_DURATION = 1.2
const DISINTEGRATE_DISTANCE = 1.6

export function AsteroidModel({ destroyed = false, onDisintegrateComplete, ...props }) {
  const { nodes, materials } = useGLTF('/assets/models/asteroid_explodable.glb')
  const groupRef = useRef(null)
  const progressRef = useRef(0)
  const finishedRef = useRef(false)

  useEffect(() => {
    if (!destroyed || !groupRef.current) {
      progressRef.current = 0
      finishedRef.current = false
      return
    }

    progressRef.current = 0
    finishedRef.current = false

    groupRef.current.traverse((child) => {
      if (!child.isMesh) {
        return
      }

      if (!child.userData.initialPosition) {
        child.userData.initialPosition = child.position.clone()
      } else {
        child.position.copy(child.userData.initialPosition)
      }

      if (!child.userData.direction) {
        child.userData.direction = new Vector3(
          MathUtils.randFloatSpread(1),
          MathUtils.randFloatSpread(1),
          MathUtils.randFloatSpread(1)
        ).normalize()
      }

      if (child.material && !child.userData.materialCloned) {
        if (Array.isArray(child.material)) {
          child.material = child.material.map((material) => {
            const cloned = material.clone()
            cloned.transparent = true
            return cloned
          })
        } else {
          child.material = child.material.clone()
          child.material.transparent = true
        }
        child.userData.materialCloned = true
      }
    })
  }, [destroyed])

  useFrame((_state, delta) => {
    if (!destroyed || !groupRef.current || finishedRef.current) {
      return
    }

    progressRef.current = Math.min(
      progressRef.current + delta / DISINTEGRATE_DURATION,
      1
    )

    const progress = progressRef.current
    groupRef.current.traverse((child) => {
      if (!child.isMesh) {
        return
      }

      const initialPosition = child.userData.initialPosition
      const direction = child.userData.direction

      if (initialPosition && direction) {
        child.position
          .copy(initialPosition)
          .addScaledVector(direction, progress * DISINTEGRATE_DISTANCE)
      }

      if (child.material) {
        if (Array.isArray(child.material)) {
          child.material.forEach((material) => {
            if (typeof material.opacity === 'number') {
              material.opacity = 1 - progress
            }
          })
        } else if (typeof child.material.opacity === 'number') {
          child.material.opacity = 1 - progress
        }
      }
    })

    if (progress >= 1 && !finishedRef.current) {
      finishedRef.current = true
      onDisintegrateComplete?.()
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null} scale={0.5}>
      <mesh name="origin" geometry={nodes.origin.geometry} material={materials.Asteroid} />
      <mesh name="Asteroid_Icosphere_cell" geometry={nodes.Asteroid_Icosphere_cell.geometry} material={materials.Asteroid} position={[0.264, 0.004, 0.566]} />
      <mesh name="Asteroid_Icosphere_cell001" geometry={nodes.Asteroid_Icosphere_cell001.geometry} material={materials.Asteroid} position={[0.289, -0.321, -0.492]} />
      <mesh name="Asteroid_Icosphere_cell002" geometry={nodes.Asteroid_Icosphere_cell002.geometry} material={materials.Asteroid} position={[-0.011, 0.011, 0.597]} />
      <mesh name="Asteroid_Icosphere_cell003" geometry={nodes.Asteroid_Icosphere_cell003.geometry} material={materials.Asteroid} position={[-0.121, -0.399, -0.511]} />
      <mesh name="Asteroid_Icosphere_cell004" geometry={nodes.Asteroid_Icosphere_cell004.geometry} material={materials.Asteroid} position={[-0.548, -0.167, -0.09]} />
      <mesh name="Asteroid_Icosphere_cell005" geometry={nodes.Asteroid_Icosphere_cell005.geometry} material={materials.Asteroid} position={[0.272, 0.295, 0.589]} />
      <mesh name="Asteroid_Icosphere_cell006" geometry={nodes.Asteroid_Icosphere_cell006.geometry} material={materials.Asteroid} position={[-0.536, -0.143, 0.175]} />
      <mesh name="Asteroid_Icosphere_cell007" geometry={nodes.Asteroid_Icosphere_cell007.geometry} material={materials.Asteroid} position={[0.004, 0.385, 0.62]} />
      <mesh name="Asteroid_Icosphere_cell008" geometry={nodes.Asteroid_Icosphere_cell008.geometry} material={materials.Asteroid} position={[-0.104, -0.587, 0.218]} />
      <mesh name="Asteroid_Icosphere_cell009" geometry={nodes.Asteroid_Icosphere_cell009.geometry} material={materials.Asteroid} position={[0.376, 0.203, -0.487]} />
      <mesh name="Asteroid_Icosphere_cell010" geometry={nodes.Asteroid_Icosphere_cell010.geometry} material={materials.Asteroid} position={[0.072, 0.19, 0.622]} />
      <mesh name="Asteroid_Icosphere_cell011" geometry={nodes.Asteroid_Icosphere_cell011.geometry} material={materials.Asteroid} position={[0.511, -0.36, 0.007]} />
      <mesh name="Asteroid_Icosphere_cell012" geometry={nodes.Asteroid_Icosphere_cell012.geometry} material={materials.Asteroid} position={[0.275, 0.409, -0.328]} />
      <mesh name="Asteroid_Icosphere_cell013" geometry={nodes.Asteroid_Icosphere_cell013.geometry} material={materials.Asteroid} position={[0.4, -0.082, -0.49]} />
      <mesh name="Asteroid_Icosphere_cell014" geometry={nodes.Asteroid_Icosphere_cell014.geometry} material={materials.Asteroid} position={[0.04, 0.275, -0.687]} />
      <mesh name="Asteroid_Icosphere_cell015" geometry={nodes.Asteroid_Icosphere_cell015.geometry} material={materials.Asteroid} position={[0.176, 0.373, 0.498]} />
      <mesh name="Asteroid_Icosphere_cell016" geometry={nodes.Asteroid_Icosphere_cell016.geometry} material={materials.Asteroid} position={[-0.086, -0.079, -0.804]} />
      <mesh name="Asteroid_Icosphere_cell017" geometry={nodes.Asteroid_Icosphere_cell017.geometry} material={materials.Asteroid} position={[-0.118, 0.035, -0.833]} />
      <mesh name="Asteroid_Icosphere_cell018" geometry={nodes.Asteroid_Icosphere_cell018.geometry} material={materials.Asteroid} position={[0.236, 0.245, -0.606]} />
      <mesh name="Asteroid_Icosphere_cell019" geometry={nodes.Asteroid_Icosphere_cell019.geometry} material={materials.Asteroid} position={[0.473, -0.353, 0.325]} />
      <mesh name="Asteroid_Icosphere_cell020" geometry={nodes.Asteroid_Icosphere_cell020.geometry} material={materials.Asteroid} position={[0.379, 0.489, -0.092]} />
      <mesh name="Asteroid_Icosphere_cell021" geometry={nodes.Asteroid_Icosphere_cell021.geometry} material={materials.Asteroid} position={[0.47, 0.1, -0.372]} />
      <mesh name="Asteroid_Icosphere_cell022" geometry={nodes.Asteroid_Icosphere_cell022.geometry} material={materials.Asteroid} position={[0.428, 0.132, 0.369]} />
      <mesh name="Asteroid_Icosphere_cell023" geometry={nodes.Asteroid_Icosphere_cell023.geometry} material={materials.Asteroid} position={[0.137, 0.578, -0.192]} />
      <mesh name="Asteroid_Icosphere_cell024" geometry={nodes.Asteroid_Icosphere_cell024.geometry} material={materials.Asteroid} position={[-0.054, 0.076, -0.837]} />
      <mesh name="Asteroid_Icosphere_cell025" geometry={nodes.Asteroid_Icosphere_cell025.geometry} material={materials.Asteroid} position={[0.687, 0.12, -0.166]} />
      <mesh name="Asteroid_Icosphere_cell026" geometry={nodes.Asteroid_Icosphere_cell026.geometry} material={materials.Asteroid} position={[0.067, 0.479, -0.506]} />
      <mesh name="Asteroid_Icosphere_cell027" geometry={nodes.Asteroid_Icosphere_cell027.geometry} material={materials.Asteroid} position={[0.088, -0.169, 0.608]} />
      <mesh name="Asteroid_Icosphere_cell028" geometry={nodes.Asteroid_Icosphere_cell028.geometry} material={materials.Asteroid} position={[0.545, 0.272, 0.15]} />
      <mesh name="Asteroid_Icosphere_cell029" geometry={nodes.Asteroid_Icosphere_cell029.geometry} material={materials.Asteroid} position={[-0.176, 0.539, -0.253]} />
      <mesh name="Asteroid_Icosphere_cell030" geometry={nodes.Asteroid_Icosphere_cell030.geometry} material={materials.Asteroid} position={[-0.002, 0.554, -0.365]} />
      <mesh name="Asteroid_Icosphere_cell031" geometry={nodes.Asteroid_Icosphere_cell031.geometry} material={materials.Asteroid} position={[-0.188, 0.402, -0.662]} />
      <mesh name="Asteroid_Icosphere_cell032" geometry={nodes.Asteroid_Icosphere_cell032.geometry} material={materials.Asteroid} position={[0.359, 0.357, 0.259]} />
      <mesh name="Asteroid_Icosphere_cell033" geometry={nodes.Asteroid_Icosphere_cell033.geometry} material={materials.Asteroid} position={[0.724, -0.307, 0.084]} />
      <mesh name="Asteroid_Icosphere_cell034" geometry={nodes.Asteroid_Icosphere_cell034.geometry} material={materials.Asteroid} position={[0.095, 0.326, -0.714]} />
      <mesh name="Asteroid_Icosphere_cell035" geometry={nodes.Asteroid_Icosphere_cell035.geometry} material={materials.Asteroid} position={[0.288, -0.073, -0.55]} />
      <mesh name="Asteroid_Icosphere_cell036" geometry={nodes.Asteroid_Icosphere_cell036.geometry} material={materials.Asteroid} position={[-0.097, 0.031, -0.686]} />
      <mesh name="Asteroid_Icosphere_cell037" geometry={nodes.Asteroid_Icosphere_cell037.geometry} material={materials.Asteroid} position={[0.658, -0.235, 0.085]} />
      <mesh name="Asteroid_Icosphere_cell038" geometry={nodes.Asteroid_Icosphere_cell038.geometry} material={materials.Asteroid} position={[-0.235, 0.092, 0.572]} />
      <mesh name="Asteroid_Icosphere_cell039" geometry={nodes.Asteroid_Icosphere_cell039.geometry} material={materials.Asteroid} position={[-0.34, -0.485, -0.397]} />
      <mesh name="Asteroid_Icosphere_cell040" geometry={nodes.Asteroid_Icosphere_cell040.geometry} material={materials.Asteroid} position={[0.211, 0.058, -0.659]} />
      <mesh name="Asteroid_Icosphere_cell041" geometry={nodes.Asteroid_Icosphere_cell041.geometry} material={materials.Asteroid} position={[-0.557, 0.279, 0.134]} />
      <mesh name="Asteroid_Icosphere_cell042" geometry={nodes.Asteroid_Icosphere_cell042.geometry} material={materials.Asteroid} position={[0.065, 0.309, -0.744]} />
      <mesh name="Asteroid_Icosphere_cell043" geometry={nodes.Asteroid_Icosphere_cell043.geometry} material={materials.Asteroid} position={[0.468, -0.315, -0.37]} />
      <mesh name="Asteroid_Icosphere_cell044" geometry={nodes.Asteroid_Icosphere_cell044.geometry} material={materials.Asteroid} position={[0.2, 0.363, -0.585]} />
      <mesh name="Asteroid_Icosphere_cell045" geometry={nodes.Asteroid_Icosphere_cell045.geometry} material={materials.Asteroid} position={[-0.467, -0.303, 0.358]} />
      <mesh name="Asteroid_Icosphere_cell046" geometry={nodes.Asteroid_Icosphere_cell046.geometry} material={materials.Asteroid} position={[-0.321, -0.448, -0.168]} />
      <mesh name="Asteroid_Icosphere_cell047" geometry={nodes.Asteroid_Icosphere_cell047.geometry} material={materials.Asteroid} position={[-0.456, 0.032, 0.497]} />
      <mesh name="Asteroid_Icosphere_cell048" geometry={nodes.Asteroid_Icosphere_cell048.geometry} material={materials.Asteroid} position={[0.684, -0.333, 0.059]} />
      <mesh name="Asteroid_Icosphere_cell049" geometry={nodes.Asteroid_Icosphere_cell049.geometry} material={materials.Asteroid} position={[-0.699, 0.004, 0.22]} />
      <mesh name="Asteroid_Icosphere_cell050" geometry={nodes.Asteroid_Icosphere_cell050.geometry} material={materials.Asteroid} position={[0.205, -0.363, 0.487]} />
      <mesh name="Asteroid_Icosphere_cell051" geometry={nodes.Asteroid_Icosphere_cell051.geometry} material={materials.Asteroid} position={[-0.132, 0.459, -0.546]} />
      <mesh name="Asteroid_Icosphere_cell052" geometry={nodes.Asteroid_Icosphere_cell052.geometry} material={materials.Asteroid} position={[-0.565, -0.423, -0.304]} />
      <mesh name="Asteroid_Icosphere_cell053" geometry={nodes.Asteroid_Icosphere_cell053.geometry} material={materials.Asteroid} position={[-0.017, 0.545, -0.201]} />
      <mesh name="Asteroid_Icosphere_cell054" geometry={nodes.Asteroid_Icosphere_cell054.geometry} material={materials.Asteroid} position={[-0.144, -0.203, 0.368]} />
      <mesh name="Asteroid_Icosphere_cell055" geometry={nodes.Asteroid_Icosphere_cell055.geometry} material={materials.Asteroid} position={[-0.282, -0.346, 0.031]} />
      <mesh name="Asteroid_Icosphere_cell056" geometry={nodes.Asteroid_Icosphere_cell056.geometry} material={materials.Asteroid} position={[0.607, -0.246, 0.356]} />
      <mesh name="Asteroid_Icosphere_cell057" geometry={nodes.Asteroid_Icosphere_cell057.geometry} material={materials.Asteroid} position={[0.688, 0.082, -0.07]} />
      <mesh name="Asteroid_Icosphere_cell058" geometry={nodes.Asteroid_Icosphere_cell058.geometry} material={materials.Asteroid} position={[0.614, -0.315, 0.197]} />
      <mesh name="Asteroid_Icosphere_cell059" geometry={nodes.Asteroid_Icosphere_cell059.geometry} material={materials.Asteroid} position={[-0.257, 0.336, -0.658]} />
      <mesh name="Asteroid_Icosphere_cell060" geometry={nodes.Asteroid_Icosphere_cell060.geometry} material={materials.Asteroid} position={[0.51, -0.003, 0.554]} />
      <mesh name="Asteroid_Icosphere_cell061" geometry={nodes.Asteroid_Icosphere_cell061.geometry} material={materials.Asteroid} position={[0.028, -0.011, -0.823]} />
      <mesh name="Asteroid_Icosphere_cell062" geometry={nodes.Asteroid_Icosphere_cell062.geometry} material={materials.Asteroid} position={[0.711, -0.095, -0.222]} />
      <mesh name="Asteroid_Icosphere_cell063" geometry={nodes.Asteroid_Icosphere_cell063.geometry} material={materials.Asteroid} position={[-0.535, -0.261, 0.016]} />
      <mesh name="Asteroid_Icosphere_cell064" geometry={nodes.Asteroid_Icosphere_cell064.geometry} material={materials.Asteroid} position={[-0.391, 0.498, -0.215]} />
      <mesh name="Asteroid_Icosphere_cell065" geometry={nodes.Asteroid_Icosphere_cell065.geometry} material={materials.Asteroid} position={[0.042, 0.136, -0.773]} />
      <mesh name="Asteroid_Icosphere_cell066" geometry={nodes.Asteroid_Icosphere_cell066.geometry} material={materials.Asteroid} position={[-0.101, 0.661, 0.02]} />
      <mesh name="Asteroid_Icosphere_cell067" geometry={nodes.Asteroid_Icosphere_cell067.geometry} material={materials.Asteroid} position={[-0.443, 0.169, -0.118]} />
      <mesh name="Asteroid_Icosphere_cell068" geometry={nodes.Asteroid_Icosphere_cell068.geometry} material={materials.Asteroid} position={[-0.269, -0.008, -0.452]} />
      <mesh name="Asteroid_Icosphere_cell069" geometry={nodes.Asteroid_Icosphere_cell069.geometry} material={materials.Asteroid} position={[-0.124, 0.195, -0.433]} />
      <mesh name="Asteroid_Icosphere_cell070" geometry={nodes.Asteroid_Icosphere_cell070.geometry} material={materials.Asteroid} position={[0.441, -0.003, -0.028]} />
      <mesh name="Asteroid_Icosphere_cell071" geometry={nodes.Asteroid_Icosphere_cell071.geometry} material={materials.Asteroid} position={[-0.297, 0.402, 0.209]} />
      <mesh name="Asteroid_Icosphere_cell072" geometry={nodes.Asteroid_Icosphere_cell072.geometry} material={materials.Asteroid} position={[0.058, 0.386, 0.185]} />
      <mesh name="Asteroid_Icosphere_cell073" geometry={nodes.Asteroid_Icosphere_cell073.geometry} material={materials.Asteroid} position={[-0.623, -0.024, -0.19]} />
      <mesh name="Asteroid_Icosphere_cell074" geometry={nodes.Asteroid_Icosphere_cell074.geometry} material={materials.Asteroid} position={[-0.561, -0.306, -0.356]} />
      <mesh name="Asteroid_Icosphere_cell075" geometry={nodes.Asteroid_Icosphere_cell075.geometry} material={materials.Asteroid} position={[0.365, -0.112, 0.285]} />
      <mesh name="Asteroid_Icosphere_cell076" geometry={nodes.Asteroid_Icosphere_cell076.geometry} material={materials.Asteroid} position={[0.148, -0.501, 0.003]} />
      <mesh name="Asteroid_Icosphere_cell077" geometry={nodes.Asteroid_Icosphere_cell077.geometry} material={materials.Asteroid} position={[0.13, 0.344, -0.675]} />
      <mesh name="Asteroid_Icosphere_cell078" geometry={nodes.Asteroid_Icosphere_cell078.geometry} material={materials.Asteroid} position={[0.144, -0.328, -0.578]} />
    </group>
  )
}

useGLTF.preload('/assets/models/Asterid_explodable.glb')
